import os
import time
from dotenv import load_dotenv
from supabase import create_client, Client

from dedup import dedup
from language_filter import language_filter
from noise_removal import noise_removal

def run_pipeline():
    # Load environment variables
    load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))
    
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_KEY")
    
    if not url or not key:
        print("Error: Missing Supabase URL or Key in .env")
        return

    supabase: Client = create_client(url, key)
    
    print("--- Starting Preprocessing Pipeline ---")
    
    # 1. Fetch raw snippets with pagination to overcome 1000-row default limit
    print("Fetching raw_snippets from Supabase...")
    
    raw_snippets = []
    page_size = 1000
    for i in range(10): # Fetch up to 10,000
        start = i * page_size
        end = start + page_size - 1
        response = supabase.table("raw_snippets").select("*").range(start, end).execute()
        
        if not response.data:
            break
            
        raw_snippets.extend(response.data)
        
        if len(response.data) < page_size:
            break
    
    initial_count = len(raw_snippets)
    print(f"Initial count: {initial_count} snippets")
    
    if initial_count == 0:
        print("No raw snippets found to process.")
        return

    # 2. Deduplication
    print("Running deduplication...")
    deduped = dedup(raw_snippets)
    dedup_count = len(deduped)
    print(f"After dedup: {dedup_count} snippets (Removed {initial_count - dedup_count})")
    
    # 3. Language Filter
    print("Running language filter...")
    lang_filtered = language_filter(deduped)
    lang_count = len(lang_filtered)
    print(f"After language filter: {lang_count} snippets (Removed {dedup_count - lang_count})")
    
    # 4. Noise Removal
    print("Running noise removal...")
    cleaned = noise_removal(lang_filtered)
    final_count = len(cleaned)
    print(f"After noise removal: {final_count} snippets (Removed {lang_count - final_count})")
    
    # 5. Push to clean_snippets
    if final_count > 0:
        print(f"Pushing {final_count} clean snippets to Supabase...")
        
        # Prepare bulk insert payload
        payload = []
        for snippet in cleaned:
            payload.append({
                "raw_id": snippet["id"],
                "source": snippet["source"],
                "text": snippet["text"],
                "metadata": snippet["metadata"]
                # processed_at is auto-generated by the DB
            })
        
        # Insert in batches of 500
        batch_size = 500
        for i in range(0, len(payload), batch_size):
            batch = payload[i:i+batch_size]
            supabase.table("clean_snippets").insert(batch).execute()
            print(f"Inserted batch {i//batch_size + 1}")
            
    print("--- Preprocessing Complete ---")

if __name__ == "__main__":
    run_pipeline()
